# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textToSpeech.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gtts import gTTS
import random


class Ui_MainWindow(object):
    def alertBox(self, title, message):
        alertMessage = QtWidgets.QMessageBox()
        alertMessage.setWindowTitle(title)
        alertMessage.setText(message)
        alertMessage.setStandardButtons(QtWidgets.QMessageBox.Ok)
        alertMessage.exec_()

    def textToSpeech(self):
        userText = str(self.textArea.toPlainText())

        if len(userText) == 0:
            self.alertBox('Blank','Please Write or Paste Your Text into text area')
        else:
            language = "id"
            num = random.randrange(100,999,2)
            getFiveChars = userText[0:5]
            fileName = "output/" + str(num) + "-" + getFiveChars + ".mp3"
            file = gTTS(text=userText,lang=language,slow=False)
            saveFile = file.save(fileName)
            if saveFile != "" or saveFile !=None:
                self.alertBox('Success','Your Audio has been generated :D')
            else:
                self.alertBox("Error","Something went wrong")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 480)
        MainWindow.setStyleSheet("background-color:orange ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 420, 141, 17))
        self.label.setStyleSheet("text-align:center")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 221, 17))
        self.label_2.setObjectName("label_2")
        self.textArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textArea.setGeometry(QtCore.QRect(20, 80, 531, 151))
        self.textArea.setStyleSheet("font-family: Calibri;\n"
"padding:8px;\n"
"color: white;\n"
"border-radius:20px;\n"
"font-weight:bold;\n"
"border: 2px solid white;")
        self.textArea.setObjectName("textArea")
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(20, 250, 531, 25))
        self.convertButton.setObjectName("convertButton")
        self.convertButton.clicked.connect(self.textToSpeech)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text-tp-Speech-Converter"))
        self.label.setText(_translate("MainWindow", "By Mamang Ozak"))
        self.label_2.setText(_translate("MainWindow", "Write or Paste Your Text Here!"))
        self.convertButton.setText(_translate("MainWindow", "Convert to Audio :D"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
